const y=document.querySelector("#year");
for(let i=2000;i<=2026;i++){let o=document.createElement("option");o.value=i;o.textContent=i;y.appendChild(o)}
const C=["No", "Nama", "Kelas", "Jenis Kelamin", "Pilihan", "Skolastik", "Wudhu", "Sholat", "Akidah Akhlak", "Hadist & doa sehari-hari", "Tajwid", "Kefasihan", "Kelancaran", "Sub Total Keagamaan Islam", "Ibadah ke Gereja", "Pelayanan di Gereja", "Lagu Pujian", "Berdoa & Membaca Alkitab", "Doa Bapa Kami", "Sepuluh Perintah Allah", "Kebiasaan Baik", "Menghormati Orang Tua", "Sub Total Keagamaan Kristen & Katolik", "Intonasi", "Artikulasi", "Volume Suara", "Pemilihan Kata", "Struktur Kalimat", "Gestur", "Ekspresi", "Kesesuaian Isi", "Kelancaran Public Speaking", "Sub Total Public Speaking", "Sikap & Perilaku", "Komunikasi", "Karakter", "Hubungan", "Dukungan", "Manajemen Waktu", "Konsistensi", "MPK - OSIS", "Komitmen", "Sub Total Wawancara", "Jumlah Nilai", "Keterangan"];
const norm=s=>String(s??"").trim().replace(/\s+/g," ").toUpperCase();
function parseCSV(t){let rows=[],row=[],cell="",q=false;for(let i=0;i<t.length;i++){let c=t[i],n=t[i+1];if(c=='"'&&q&&n=='"'){cell+='"';i++;continue}if(c=='"'){q=!q;continue}if(c==","&&!q){row.push(cell);cell="";continue}if((c=="\n"||c=="\r")&&!q){if(c=="\r"&&n=="\n")i++;row.push(cell);cell="";if(row.some(v=>v.trim()))rows.push(row);row=[];continue}cell+=c}if(cell||row.length){row.push(cell);if(row.some(v=>v.trim()))rows.push(row)}if(!rows.length)return[];let h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??"").trim()])))}
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
function render(p){
 const fixed=C.slice(0,6), islam=C.slice(6,14), kristen=C.slice(14,23), pub=C.slice(23,33), waw=C.slice(33,43), tail=["Jumlah Nilai"];
 const th=(x,r=1)=>`<th rowspan="${r}">${esc(x)}</th>`;
 const group=(x,a)=>`<th colspan="${a.length}">${esc(x)}</th>`;
 const subs=a=>a.map(x=>`<th>${esc(x)}</th>`).join("");
 document.querySelector("#scoreTable").innerHTML=
 `<thead><tr class="group-row">${fixed.map(x=>th(x,2)).join("")}${group("Keagamaan Islam",islam)}${group("Keagamaan Kristen & Katolik",kristen)}${group("Public Speaking",pub)}${group("Wawancara",waw)}${tail.map(x=>th(x,2)).join("")}</tr><tr class="sub-row">${subs(islam)}${subs(kristen)}${subs(pub)}${subs(waw)}</tr></thead><tbody><tr>${[...C.filter(x=>x!=="Keterangan")].map(x=>`<td class="${x==="Jumlah Nilai"?"final":""}">${esc(p[x])||"—"}</td>`).join("")}</tr></tbody>`;
}
document.querySelector("#form").addEventListener("submit",async e=>{e.preventDefault();let m=document.querySelector("#msg");m.textContent="";try{let r=await fetch("data/peserta.csv?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw 0;let d=parseCSV(await r.text()),p=d.find(x=>norm(x.Nama)==norm(document.querySelector("#name").value)&&norm(x.Kelas)==norm(document.querySelector("#class").value)&&x.tahun_lahir==y.value&&norm(x.Pilihan)==norm(document.querySelector("#division").value));if(!p){m.textContent="Data tidak ditemukan. Periksa nama, kelas, tahun lahir, dan pilihan.";return}let s=(p.status||"red").toLowerCase(),card=document.querySelector("#resultCard");card.className="result "+s;document.querySelector("#status").textContent=s=="blue"?"LOLOS":s=="yellow"?"LOLOS BERSYARAT":"TIDAK LOLOS";document.querySelector("#title").textContent=p.judul||"Hasil Seleksi";document.querySelector("#rname").textContent=p.Nama||"—";document.querySelector("#rclass").textContent=p.Kelas||"—";document.querySelector("#rdivision").textContent=p.Pilihan||"—";document.querySelector("#desc").textContent=p.keterangan||"Silakan mengikuti informasi selanjutnya dari panitia.";document.querySelector("#icon").textContent=s=="blue"?"✓":s=="yellow"?"!":"×";render(p);document.querySelector("#result").classList.remove("hidden");document.querySelector("#result").scrollIntoView({behavior:"smooth",block:"start"})}catch(e){m.textContent="Database belum tersedia. Pastikan data/peserta.csv sudah di-upload ke GitHub."}});
document.querySelector("#reset").onclick=()=>{document.querySelector("#form").reset();document.querySelector("#result").classList.add("hidden");document.querySelector("#cek").scrollIntoView({behavior:"smooth"})};